var data = {
	images: [
		{
			src: [""],
			thumbnail: "",
			title: "",
			artist: "",
			artist_url: "",
			art_url: "",
			desc: "",
			date_str: "",
			tags: ["sfw", "nsfw", "extreme", "fireemblem", "bravelydefault", "lif", "thrasir", "veronica", "ylgr", "tiz", "agnes", "edea", "ringabel", "basedonfic", "gift"],
			hidden: true
		},
		{
			src: ["https://cdn.imgchest.com/files/7bwckdzba67.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/yxkczg62bl7.png",
			title: "UntitledLifthrasir Enjoyer Birthday Gift Art",
			artist: "j",
			artist_url: "https://x.com/abgthrasir",
			art_url: null,
			desc: "winter is the best season for lifthrasir enjoyers",
			date_str: "Feb 12 2023",
			tags: ["sfw", "fireemblem", "thrasir", "lif", "gift"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/y2pckolzqv7.webp"],
			thumbnail: "https://cdn.imgchest.com/files/y8xcnlvma24.png",
			title: "Untitled Courier Bunny Gift Art",
			artist: "DarknesS",
			artist_url: "https://bsky.app/profile/did:plc:3xdyjimydh6q3b6cg5z26mu3",
			art_url: null,
			desc: "Two Emblian princesses enjoy the company of a soft friend.",
			date_str: "Feb 12 2023",
			tags: ["sfw", "fireemblem", "thrasir", "veronica", "gift"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/yq9c3emm9b4.webp"],
			thumbnail: "https://cdn.imgchest.com/files/4z9cvwrr2w7.png",
			title: "Outrun the Wolves",
			artist: "DarknesS",
			artist_url: "https://bsky.app/profile/did:plc:3xdyjimydh6q3b6cg5z26mu3",
			art_url: null,
			desc: "hel generals bein cool",
			date_str: "Feb 12 2023",
			tags: ["sfw", "fireemblem", "thrasir", "lif", "gift"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/yxkczgaodo7.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/45xcv93wdg7.png",
			title: "Endless Horizons",
			artist: "missdash",
			artist_url: "https://bsky.app/profile/did:plc:3xdyjimydh6q3b6cg5z26mu3",
			art_url: "https://x.com/missdash_/status/1460039421525311488",
			desc: "Líf and Thrasir join the Askran Royal Guard, for a time.",
			date_str: "Nov 15 2021",
			tags: ["sfw", "fireemblem", "thrasir", "lif", "basedonfic"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/7pjcqwrodg7.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/yd5cerplak4.png",
			title: "Speedwells",
			artist: "fubbz",
			artist_url: "https://bsky.app/profile/fyllophobia.bsky.social",
			art_url: null,
			desc: "Thrasir's visits are brief, but Veronica appreciates them all the same.",
			date_str: "Feb 12 2024",
			tags: ["sfw", "fireemblem", "thrasir", "gift", "veronica"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/46acqg89e87.png"],
			thumbnail: "https://cdn.imgchest.com/files/yxkczqvdod7.png",
			title: "Promises Not Necessary",
			artist: "fubbz",
			artist_url: "https://bsky.app/profile/fyllophobia.bsky.social",
			art_url: null,
			desc: "Thrasir is bad at being a June Bride",
			date_str: null,
			tags: ["sfw", "fireemblem", "thrasir", "gift", "basedonfic"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/7mmc9rmwjp7.png", "https://cdn.imgchest.com/files/49zc2velmxy.png", "https://cdn.imgchest.com/files/4nec8lbrgv4.png", "https://cdn.imgchest.com/files/7bwck23qab7.png"],
			thumbnail: "https://cdn.imgchest.com/files/yd5cer83rj4.png",
			title: "Winter Comfort",
			artist: "Sierra117renner",
			artist_url: "https://www.instagram.com/sierra117renner/",
			art_url: null,
			desc: "Thrasir has a warm drink and a festive outfit.",
			date_str: "Dec 20 2020",
			tags: ["sfw", "fireemblem", "thrasir"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/7pjcqkbeda7.png"],
			thumbnail: "https://cdn.imgchest.com/files/7bwck23rla7.png",
			title: "Devoted Líf",
			artist: "Sierra117renner",
			artist_url: "https://www.instagram.com/sierra117renner/",
			art_url: null,
			desc: "Líf wearing his Day of Devotion outfit.",
			date_str: "May 12 2021",
			tags: ["sfw", "fireemblem", "lif"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/y8xcnqv6ag4.png"],
			thumbnail: "https://cdn.imgchest.com/files/yrgcn9bdxl4.png",
			title: "Buni Líf",
			artist: "Sierra117renner",
			artist_url: "https://www.instagram.com/sierra117renner/",
			art_url: null,
			desc: "Líf wearing a Spring outfit. (Years later I realize his chest is not blue...)",
			date_str: "May 13 2021",
			tags: ["sfw", "fireemblem", "lif"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/46acqb999j7.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/ye3c2dllab4.png",
			title: "Life Adjusts",
			artist: "Memeh",
			artist_url: "https://memeh.carrd.co/",
			art_url: "https://x.com/lazymimium/status/1401337716940447753",
			desc: "Two generals share a quiet moment together.",
			date_str: "Jun 2 2021",
			tags: ["sfw", "fireemblem", "thrasir", "lif", "basedonfic"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/4jdcvjnd3n4.png"],
			thumbnail: "https://cdn.imgchest.com/files/yd5cerjvga4.png",
			title: "Radiant",
			artist: "Dux",
			artist_url: "https://bsky.app/profile/dux-draws.bsky.social",
			art_url: null,
			desc: "two hel generals at the beach, what will they do",
			date_str: "Aug 22 2022",
			tags: ["sfw", "fireemblem", "thrasir", "lif", "basedonfic"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/y8xcnkvn3l4.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/y8xcnlqqlb4.png",
			title: "Untitled Bunny Suit Gift Art",
			artist: "DarknesS",
			artist_url: "https://bsky.app/profile/did:plc:3xdyjimydh6q3b6cg5z26mu3",
			art_url: "https://bsky.app/profile/exaltedbrand.bsky.social/post/3lhyl4tr73k2p",
			desc: "fighting heroes by moonlight / winning buns by daylight / never running from a real fight / she is the one wishing me a happy birthday 🌻🎂",
			date_str: "Feb 12 2025",
			tags: ["sfw", "fireemblem", "thrasir", "gift"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/7mmc9rmgwv7.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/y2pckon9w97.png",
			title: "A New Friend",
			artist: "Trevor",
			artist_url: "https://bsky.app/profile/ddbofthestars.bsky.social",
			art_url: "https://x.com/ddbofthestars/status/1740042675263586684",
			desc: "Veronica offers her dear friend a special Emblian courier to return the kindness Yglr showed her years prior with the gift of Bolt, the black-colored Niflese courier rabbit.",
			date_str: "December 27 2025",
			tags: ["sfw", "fireemblem", "veronica", "ylgr", "basedonfic", "gift"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/4z9cvwjbkb7.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/7ogcbkj82zy.png",
			title: "The Missing Flock",
			artist: "adalheidis",
			artist_url: "https://bsky.app/profile/adalheidis.bsky.social",
			art_url: "https://urbydizzy.tumblr.com/post/85339455187/adalheidis-i-looked-into-sketches-i-did-and",
			desc: "The others teased him about it, of course. That no matter how long or far they traveled, Tiz would always be a shepherd.",
			date_str: "May 14 2010",
			tags: ["sfw", "bravelydefault", "tiz", "agnes", "edea", "ringabel", "basedonfic", "request"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/45xcv9nz8v7.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/7lxcpdz9mo7.png",
			title: "Best Said Plans",
			artist: "Anonymous (Trapinchmon)",
			artist_url: "https://trapinchmon.tumblr.com/",
			art_url: "https://urbydizzy.tumblr.com/post/82714477493/a-really-kind-anon-drew-this-based-on-my-story",
			desc: "A gift from an anonymous artist (later identified with permission) on the Bravely Default Kink Meme post of the fic of the same name.",
			date_str: "April 14 2014",
			tags: ["sfw", "bravelydefault", "tiz", "agnes", "basedonfic", "gift"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/yvdcwd8zbey.jpg", "https://cdn.imgchest.com/files/yxkczgdvjd7.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/7pjcqw9bx67.png",
			title: "Cadell, Dragon of the Stars",
			artist: "47ness",
			artist_url: "https://47ness.carrd.co/",
			art_url: "https://47ness.tumblr.com/post/189323031026/dragonship-concepts-final-design-original",
			desc: "A design commission for a spacecraft with a special artificial consciousness called a 'Dragon'.",
			date_str: "Nov 17 2019",
			tags: ["sfw", "azureexpanse"],
			hidden: false
		},
		{
			src: [""],
			thumbnail: "",
			title: "",
			artist: "",
			artist_url: "",
			art_url: "",
			desc: "",
			date_str: "",
			tags: [""],
			hidden: true
		}
	]
};
